
export interface ILoan {
  prestamoId: string
  clienteId: number
  nombres: string
  apellidoPaterno: string
  apellidoMaterno: string
  direccion: string
  noExterior: string
  noInterior?: string
  colonia: string
  codigoPostal: number
  municipio: string
  estado: string
  noDeContrato: string
  agente: string
  gerencia: string
  semana: number
  anio: number
  plazo: number
  montoOtorgado: number
  cargo: number
  totalAPagar: number
  primerPago: number
  tarifa: number
  saldosMigrados?: number
  wkDescu?: number
  descuento: number
  porcentajeCobrado: number
  multas: number
  wkRefi?: string
  refin?: string
  externo?: string
  saldo: number
  cobrado: number
  tipoDeCredito: string
  aclaracion?: string
  nombresAval: string
  apellidoPaternoAval: string
  apellidoMaternoAval: string
  direccionAval: string
  noExteriorAval?: string
  noInteriorAval?: string
  coloniaAval: string
  codigoPostalAval: number
  poblacionAval: string
  estadoAval: string
  telefonoAval: string
  telefonoCliente: string
  diaDePago: string
  gerenteEnTurno: string
  agente2: string
  status: string
  capturista: string
  noServicio: string
  tipoDeCliente: string
  identificadorCredito: string
  seguridad: string
  depuracion?: string
  folioDePagare?: string
  saldoAlIniciarSemana: number
}